// Manually edited. Originally generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions web = const FirebaseOptions(
    apiKey: 'AIzaSyCPMD9F8WdalFNUW-jD-8Vw19EinzQP4Z0',
    appId: '1:519380064836:web:e3d7a48dc5eec2cffeba11',
    messagingSenderId: '519380064836',
    projectId: 'cashbackmax-126eb',
    authDomain: 'cashbackmax-126eb.firebaseapp.com',
    storageBucket: 'cashbackmax-126eb.firebasestorage.app',
    measurementId: 'G-MWQKZMG09R',
  );

  static FirebaseOptions android = const FirebaseOptions(
    apiKey: 'AIzaSyCPMD9F8WdalFNUW-jD-8Vw19EinzQP4Z0',
    appId: '1:519380064836:android:79421634381ef16cfeba11',
    messagingSenderId: '519380064836',
    projectId: 'cashbackmax-126eb',
    storageBucket: 'cashbackmax-126eb.firebasestorage.app',
  );

  static FirebaseOptions ios = const FirebaseOptions(
    apiKey: 'AIzaSyCPMD9F8WdalFNUW-jD-8Vw19EinzQP4Z0',
    appId: '1:519380064836:ios:9e4906999f18508dfeba11',
    messagingSenderId: '519380064836',
    projectId: 'cashbackmax-126eb',
    storageBucket: 'cashbackmax-126eb.firebasestorage.app',
    iosBundleId: 'com.radra.cashbackRewardsPointsMaximiser',
  );

  static FirebaseOptions macos = ios;

  static FirebaseOptions windows = web;
}
