// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDROI6rPQKx2uHrZbS5xTMETHi-3-e1zUk',
    appId: '1:918477263203:web:001f0ffa5f6a31731b0356',
    messagingSenderId: '918477263203',
    projectId: 'cashbackmax-d17de',
    authDomain: 'cashbackmax-d17de.firebaseapp.com',
    storageBucket: 'cashbackmax-d17de.firebasestorage.app',
    measurementId: 'G-0NDXM1TK7R',
  );

  static FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBl7q8ZLb25snLOcS4htNLu2dF4uj9HWAU',
    appId: '1:918477263203:android:cde6ba53ee1a69db1b0356',
    messagingSenderId: '918477263203',
    projectId: 'cashbackmax-d17de',
    storageBucket: 'cashbackmax-d17de.firebasestorage.app',
  );

  static FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1WEiVcCsNvEmEpsAy042w4C3uw0GuUH4',
    appId: '1:918477263203:ios:f42ef8983fc45c441b0356',
    messagingSenderId: '918477263203',
    projectId: 'cashbackmax-d17de',
    storageBucket: 'cashbackmax-d17de.firebasestorage.app',
    iosBundleId: 'com.radra.cashbackRewardsPointsMaximiser',
  );

  static FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA1WEiVcCsNvEmEpsAy042w4C3uw0GuUH4',
    appId: '1:918477263203:ios:587e7bc5b5238bba1b0356',
    messagingSenderId: '918477263203',
    projectId: 'cashbackmax-d17de',
    storageBucket: 'cashbackmax-d17de.firebasestorage.app',
    iosBundleId: 'com.example.cashbackRewardsPointsMaximiser',
  );

  static FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDROI6rPQKx2uHrZbS5xTMETHi-3-e1zUk',
    appId: '1:918477263203:web:831d54b871a10e9f1b0356',
    messagingSenderId: '918477263203',
    projectId: 'cashbackmax-d17de',
    authDomain: 'cashbackmax-d17de.firebaseapp.com',
    storageBucket: 'cashbackmax-d17de.firebasestorage.app',
    measurementId: 'G-S3HRR7WQ44',
  );

}
